/**
 * Loads public/geo/karnataka-regions.geojson (the four persona regions,
 * generated by backend/app/data/build_karnataka_regions_geo.py) once, with a
 * module-level cache. `null` while loading or if the file is missing.
 */

import type { Feature, FeatureCollection, MultiPolygon, Polygon } from "geojson";
import { useEffect, useState } from "react";

import type { RegionId } from "@/lib/worldview";
import { assetUrl } from "@/lib/worldview/api";

export interface RegionFeatureProps {
  regionId: RegionId;
  name: string;
  shortName: string;
  color: [number, number, number];
  labelPoint: [number, number];
  districtIds: string[];
  bbox: [number, number, number, number];
}

export type RegionFeature = Feature<Polygon | MultiPolygon, RegionFeatureProps>;
export type RegionFeatureCollection = FeatureCollection<Polygon | MultiPolygon, RegionFeatureProps>;

const URL = assetUrl("geo/karnataka-regions.geojson");

let cache: RegionFeatureCollection | null = null;
let inflight: Promise<RegionFeatureCollection | null> | null = null;

function ensure(): Promise<RegionFeatureCollection | null> {
  if (cache) return Promise.resolve(cache);
  inflight ??= fetch(URL)
    .then((r) => (r.ok ? (r.json() as Promise<RegionFeatureCollection>) : null))
    .catch(() => null)
    .then((geo) => {
      cache = geo;
      return geo;
    });
  return inflight;
}

export function useRegionGeo(): RegionFeatureCollection | null {
  const [geo, setGeo] = useState<RegionFeatureCollection | null>(cache);
  useEffect(() => {
    if (cache) return;
    let alive = true;
    void ensure().then((g) => {
      if (alive) setGeo(g);
    });
    return () => {
      alive = false;
    };
  }, []);
  return geo;
}
