"""
Wires the pipeline stages into a LangGraph StateGraph. Two topologies,
selected by `mode` at graph-construction time in `build_graph()`:

    basic/medium/high (unchanged): source -> research -> cluster -> resolve -> deflect -> synthesize -> END
    extrahigh: source -> research -> geo_resolve -> infer_regions -> cluster -> resolve -> deflect -> deflect_states -> synthesize -> condition_regions -> condition_states -> END

`source` is small enough (fan out to the two connectors, flatten into
`state["posts"]`) that it's defined here rather than as its own node file.
Every other stage lives in graph/nodes/ and was built to the exact
`(state, emit, ...)` signature this module calls. extrahigh's `infer_regions`/
`cluster`/`resolve`/`deflect` bind to functions that group posts into
AGENT-INFERRED REGIONS (which can span several districts and cross multiple
state boundaries — see graph/nodes/infer_regions.py's module docstring) and
cluster/extract deflections PER REGION instead of once globally or per fixed
administrative state. `deflect_states` runs right after (the same
region-mode clusters, re-grouped by each district's own TRUE administrative
state rather than a region's representative one -- see
extract_deflections_per_state's own docstring). `synthesize` is the same
function either way, but behaves differently under the hood in extrahigh: it
produces a region-BLIND national baseline instead of the final answer,
snapshotting it to `state["baseline_answer_segments"]` for both trailing
conditioning passes to read. extrahigh's trailing `condition_regions` (two-
pass synthesis pass 2) adds region-specific contrast on top, and the new
`condition_states` (pass 3, dual-source-separated: mainstream/official
research vs. social-media clusters, per administrative state) runs after
it and now owns the run's true completion event -- see
deflection_and_synthesis.py's module docstring. Neither trailing node exists
in the basic/medium/high topology.

extrahigh's `research` node ALSO behaves differently under the hood: instead
of the angle-based `get_research` call every other mode uses, it fires one
targeted research call PER STATE (`gather_research_per_state`, see
graph/nodes/research.py) -- geographic sweep, not topical-angle sweep, for
this mode only.

The graph is rebuilt per request (cheap — this isn't a compiled model) so each
request gets its own `emit` closure without threading dependency-injection
through LangGraph's config machinery. Building two different topologies in
that same per-request construction is consistent with, not a departure from,
that existing cost model — `mode` is already known before `ainvoke` runs, so
this is a graph-construction-time choice, not something that needs LangGraph's
`add_conditional_edges` runtime-predicate machinery.
"""

from __future__ import annotations

import asyncio
import itertools
import json
import re

from langgraph.graph import END, StateGraph

from ..config import DATA_DIR, Settings
from ..connectors.base import LLMClient, SourceConnector, SourcedPost
from ..connectors.llm import get_llm_client
from ..connectors.sources import get_reddit_connector, get_youtube_connector
from ..data.language_regions import detect_script_region
from ..data.subreddit_map import (
    STATE_PRIORITY_ORDER,
    STATE_SUBREDDIT,
    _state_names_from_gazetteer,
    lookup_subreddit,
)
from ..reasoning_modes import (
    FRAMING_COUNT,
    REDDIT_PER_STATE_LIMIT,
    YOUTUBE_POSTS_PER_FRAMING_CAP,
    LlmProvider,
    ResearchMode,
)
from ..schema import CollectionCounts, StatusEvent
from .nodes.cluster_viewpoints import (
    cluster_viewpoints,
    cluster_viewpoints_per_region,
    cluster_viewpoints_per_state,
)
from .nodes.deflection_and_synthesis import (
    condition_regions,
    condition_states,
    extract_deflections,
    extract_deflections_per_region,
    extract_deflections_per_state,
    synthesize_answer,
)
from .nodes.geo_resolve import resolve_posts_geography
from .nodes.infer_regions import infer_regions
from .nodes.research import gather_research
from .nodes.resolve_district import finalize_districts, resolve_districts
from .state import EmitFn, PipelineState, RawPost, new_pipeline_state

_gazetteer_cache: dict | None = None
_district_centroids_cache: dict | None = None


def load_gazetteer() -> dict:
    global _gazetteer_cache
    if _gazetteer_cache is None:
        with open(f"{DATA_DIR}/district_gazetteer.json", encoding="utf-8") as f:
            _gazetteer_cache = json.load(f)
    return _gazetteer_cache


def load_district_centroids() -> dict:
    """district_id -> [lng, lat], generated by data/build_district_centroids.py
    from the same source GeoJSON load_gazetteer() reads -- see that script's
    module docstring. Consumed by infer_regions.py's propose_regions prompt
    (a coarse geographic-sanity signal for the LLM, not a required input --
    an empty/missing file just means every group's districts carry
    centroid=None, which propose_regions already tolerates)."""
    global _district_centroids_cache
    if _district_centroids_cache is None:
        try:
            with open(f"{DATA_DIR}/district_centroids.json", encoding="utf-8") as f:
                _district_centroids_cache = json.load(f)
        except FileNotFoundError:
            print(
                "[build] district_centroids.json not found -- run "
                "`python -m app.data.build_district_centroids` to generate it; "
                "region-inference will proceed without centroid data",
                flush=True,
            )
            _district_centroids_cache = {}
    return _district_centroids_cache


def counts_from_state(state: PipelineState) -> CollectionCounts:
    return CollectionCounts(
        postsCollected=state["posts_collected"],
        districtsResolved=state["districts_resolved"],
        clustersFound=state["clusters_found"],
        deflectionsFound=state["deflections_found"],
        sourcesGathered=len(state.get("research_documents", [])),
        regionsFound=len(state.get("regions") or {}),
    )


# ── Reasoning mode -> volume/thoroughness, NOT geographic coverage ──────────
# Geographic coverage is always the full STATE_PRIORITY_ORDER regardless of
# mode (see reasoning_modes.py's module docstring for why: partial state
# coverage would directly undermine the product's cross-India-representation
# point). What mode actually controls: how many distinct regional/cultural
# framings get searched for (FRAMING_COUNT), how many posts each state's
# Reddit search asks for (REDDIT_PER_STATE_LIMIT), and how many posts each
# YouTube framing-search keeps (YOUTUBE_POSTS_PER_FRAMING_CAP).
_MAX_CONCURRENT_FETCHES = 6

# Below this many substantive "words" (Unicode-aware — covers Hindi/Bengali/
# Tamil/etc. scripts too, not just Latin), a post is dropped before it ever
# reaches clustering. A cluster built from "Yes", "🙏🙏🙏", or a single word
# has no actual stance to summarize -- any labeler, stub or real LLM alike,
# can only echo the raw text back, which is exactly what reads as a bogus
# "viewpoint" instead of a genuine one.
_MIN_SIGNAL_WORDS = 4
_WORD_RE = re.compile(r"\w{2,}", re.UNICODE)


def _is_low_signal(text: str) -> bool:
    return len(_WORD_RE.findall(text)) < _MIN_SIGNAL_WORDS


def _is_quota_exceeded(exc: Exception) -> bool:
    """True if `exc` is YouTube Data API's daily-quota-exhausted error (HTTP
    429, `reason: rateLimitExceeded`, distinct from an ordinary transient
    failure). Detected two ways: the structured HttpError status code when
    available, and a plain string match otherwise -- keeps this robust to
    whichever shape actually reaches a given call site (asyncio.to_thread
    wrapping in connectors/sources.py's YouTubeConnector.search means the
    original exception type does survive, but checking the message text too
    costs nothing and guards against that ever changing)."""
    try:
        from googleapiclient.errors import HttpError

        if isinstance(exc, HttpError) and getattr(exc, "status_code", None) == 429:
            return True
        if isinstance(exc, HttpError) and getattr(getattr(exc, "resp", None), "status", None) == 429:
            return True
    except ImportError:  # pragma: no cover -- googleapiclient always installed here
        pass
    return "quota" in str(exc).lower()


# Relevance gate: runs once per post (hundreds per pipeline run) via the
# run's OWN LLMClient (llm.judge_text_relevance), not a separately-hardcoded
# local model -- this used to hardcode a local Ollama model specifically to
# avoid multiplying a paid provider's per-post cost, but that made the whole
# gate fragile to a machine-specific detail (the hardcoded model tag not
# being pulled locally silently failed the check open, defeating the gate --
# confirmed happened in practice). Routing through `llm` instead means it
# rides whatever provider the run is already using -- for the app's default,
# gemma_remote, that's free and always available, so the original cost
# concern doesn't even apply; for a genuinely metered provider, this is one
# extra call per post same as any other per-post LLM step already in this
# pipeline (e.g. resolve_district.py's extract_place_mentions).
#
# An embedding-similarity threshold was tried first and rejected: real
# on-topic posts and genuinely off-topic ones didn't separate cleanly at any
# single cosine-similarity cutoff (a threshold that caught obvious spam also
# dropped a real "dropped out to work the harvest" testimony), so this asks
# the model the actual question in words instead of proxying it through
# vector distance.
_RELEVANCE_CONCURRENCY = 6  # mirrors RemoteGemmaLLMClient's own semaphore width


async def _is_relevant(llm: LLMClient, text: str, query: str, framings: list[str]) -> bool:
    framing_line = "; ".join(framings) if framings else "(no specific known framings)"
    question = (
        f'Topic: "{query}"\n'
        f"Known angles on this topic: {framing_line}\n\n"
        f'Post: "{text}"\n\n'
        "Is this post substantively about the topic above -- even tangentially, e.g. "
        "a specific complaint, a skeptical take, or a related opinion? Off-topic chatter, "
        "spam, or garbled/nonsense text is NOT relevant."
    )
    return await llm.judge_text_relevance(question)


async def _filter_by_relevance(posts: list[RawPost], query: str, framings: list[str], llm: LLMClient) -> list[RawPost]:
    """Drop posts the run's own LLM judges off-topic. Two things slip past
    the word-count check in `_is_low_signal` and land here instead: unrelated
    comment-thread noise on an otherwise on-topic video (real words, wrong
    topic), and garbled/corrupted text (real word-shaped tokens, no actual
    meaning) -- the latter also happens to be a known trigger for a paid
    LLM's safety classifier to refuse the label/paraphrase call outright, so
    filtering it here avoids that failure mode too, not just the bogus
    cluster it produces.

    Fails open at THIS call site whenever an exception actually propagates
    (keeps the post rather than dropping it) -- a quality gate shouldn't cost
    real data over one bad call. Note `llm.judge_text_relevance` itself fails
    CLOSED (False, not a raise) on its own internal errors per that method's
    documented contract (region_kb.py's cache-judge use of the same method
    depends on that), so a systemic provider outage here reads as "nothing is
    relevant" rather than tripping this function's own except-branch --
    already-logged inside judge_text_relevance either way, and the pipeline's
    zero-posts path (see source_posts) handles the resulting empty corpus
    gracefully rather than crashing, so this isn't a silent-corruption risk,
    just a less graceful degradation than a true fail-open would be.
    """
    if not posts:
        return posts

    semaphore = asyncio.Semaphore(_RELEVANCE_CONCURRENCY)

    async def check(post: RawPost) -> bool:
        async with semaphore:
            try:
                return await _is_relevant(llm, post["text"], query, framings)
            except Exception as exc:  # noqa: BLE001
                print(f"[source_posts] relevance check failed, keeping post: {exc}", flush=True)
                return True

    keep_flags = await asyncio.gather(*(check(post) for post in posts))

    kept = [post for post, keep in zip(posts, keep_flags) if keep]
    dropped = len(posts) - len(kept)
    if dropped:
        print(f"[source_posts] dropped {dropped} off-topic post(s) before clustering (relevance filter)", flush=True)
    return kept


async def source_posts(
    state: PipelineState,
    emit: EmitFn,
    reddit: SourceConnector,
    youtube: SourceConnector,
    llm: LLMClient,
    gazetteer: dict,
) -> PipelineState:
    """First pipeline stage: a BALANCED multi-state, multi-framing fan-out,
    not one flat keyword search. Geographic coverage is always the full
    region-interleaved state list (see data/subreddit_map.py's
    STATE_PRIORITY_ORDER) -- the "reasoning mode" (state["mode"],
    basic/medium/high) instead scales how many distinct regional/cultural
    framings of the topic get searched for (see llm.suggest_framings) and how
    many posts get pulled per state/framing, so the corpus is a deliberate
    cross-India sample of the topic's actual substantive variation, not an
    emergent, population/activity-biased one, and not just whatever generic
    reactions a bare keyword search happens to surface.

    Reddit is targeted directly at each state's subreddit (a real geographic
    signal), one search per state -- but WITHOUT real Reddit credentials
    configured (see connectors/sources.py's NullSourceConnector), this
    contributes zero posts, silently leaving YouTube as the only real source.
    YouTube search has no native per-state filter, so it also runs one search
    per FRAMING (the axis it can actually discriminate on) -- but framing-only
    search has no structural guarantee of reaching every region: a bare
    topic's real-world YouTube index tends to skew toward whichever
    language/region already dominates that platform for it (observed in
    practice: a plain "Diwali" search returns almost entirely North-Indian/
    Hindi-centric results, silently starving South India and the Northeast of
    any real signal to cluster on, no matter how the clustering stage is
    tuned downstream). So YouTube ALSO gets an explicit per-state search pass
    below (query + state name), restoring the same "every state gets an
    actual attempt" guarantee Reddit's per-state design already intended, on
    the one source that's actually working. resolve_district's hierarchy plus
    the clustering stage remain the sole sources of truth for where a post
    resolves and what viewpoint it actually expresses -- this only widens
    what gets a chance to be sourced in the first place.
    """
    mode: ResearchMode = state["mode"]
    target_states = STATE_PRIORITY_ORDER
    reddit_limit = REDDIT_PER_STATE_LIMIT[mode]
    youtube_limit = YOUTUBE_POSTS_PER_FRAMING_CAP[mode]
    state_names = _state_names_from_gazetteer(gazetteer)

    known_framings = await llm.suggest_framings(state["query"], FRAMING_COUNT[mode])
    state["framings"] = known_framings  # kept empty if the LLM found none — used later to
    # ground synthesis in real-world knowledge; do NOT fall back to [query] here, that
    # would misrepresent "no known regional variation" as if it were one.
    framings = known_framings or [state["query"]]

    def framing_for(i: int) -> str:
        return framings[i % len(framings)]

    await emit(
        StatusEvent(
            queryRunId=state["query_run_id"],
            ticker=(
                f"Surveying {len(target_states)} states across "
                f"{len(framings)} angle{'s' if len(framings) != 1 else ''} for "
                f"“{state['query']}” ({mode} mode)…"
            ),
            phase="sourcing",
            counts=counts_from_state(state),
            progress=0.02,
        )
    )

    semaphore = asyncio.Semaphore(_MAX_CONCURRENT_FETCHES)
    # Set the first time any YouTube call fails with a quota-exceeded error --
    # checked after sourcing so a fully-empty result reads as "quota hit"
    # rather than a silent, unexplained "0 posts" (see the check right after
    # the gather below, and _is_quota_exceeded's own docstring).
    youtube_quota_hit = False

    async def fetch_reddit(index: int, state_code: str) -> list[SourcedPost]:
        subreddit = STATE_SUBREDDIT.get(state_code)
        search_subreddit = getattr(reddit, "search_subreddit", None)
        if not subreddit or search_subreddit is None:
            return []
        async with semaphore:
            try:
                return await search_subreddit(subreddit, framing_for(index), reddit_limit)
            except Exception as exc:  # noqa: BLE001 — one state's failure must not kill the run
                print(f"[source_posts] reddit/{subreddit} failed: {exc}", flush=True)
                return []

    async def fetch_youtube(framing: str) -> list[SourcedPost]:
        nonlocal youtube_quota_hit
        async with semaphore:
            try:
                return await youtube.search(framing, youtube_limit)
            except Exception as exc:  # noqa: BLE001
                if _is_quota_exceeded(exc):
                    youtube_quota_hit = True
                print(f"[source_posts] youtube/{framing!r} failed: {exc}", flush=True)
                return []

    async def fetch_youtube_state(state_code: str) -> list[SourcedPost]:
        """Complementary to fetch_youtube above -- see source_posts' own
        docstring for why this exists now. `reddit_limit` (not youtube_limit)
        on purpose: this stands in for the per-state volume Reddit's own
        design intended to contribute, not another framing-scale pull."""
        nonlocal youtube_quota_hit
        name = state_names.get(state_code)
        if not name:
            return []
        async with semaphore:
            try:
                return await youtube.search(f"{state['query']} {name}", reddit_limit)
            except Exception as exc:  # noqa: BLE001
                if _is_quota_exceeded(exc):
                    youtube_quota_hit = True
                print(f"[source_posts] youtube-state/{name!r} failed: {exc}", flush=True)
                return []

    # The per-state YouTube pass costs a flat 100 quota units PER STATE
    # (search.list's cost doesn't scale with maxResults -- see
    # connectors/sources.py's own comment) -- 36 states is 3600 units on top
    # of the framing-based searches, which exhausted a real day's YouTube
    # quota in practice once several runs stacked up. Scoped to extrahigh
    # only: that's the mode this exists for (the qualitatively-different,
    # every-viewpoint-traceable-to-a-region pipeline), not basic/medium/high,
    # which don't need the same exhaustive guarantee and shouldn't pay for it
    # on every single test query.
    state_youtube_tasks = (
        [fetch_youtube_state(code) for code in target_states] if mode == "extrahigh" else []
    )

    fetched = await asyncio.gather(
        *(fetch_reddit(i, code) for i, code in enumerate(target_states)),
        *(fetch_youtube(framing) for framing in framings),
        *state_youtube_tasks,
    )

    posts: list[RawPost] = []
    dropped = 0
    for i, p in enumerate(itertools.chain.from_iterable(fetched)):
        if _is_low_signal(p["text"]):
            dropped += 1
            continue
        posts.append(
            RawPost(
                id=p.get("id") or f"p{i}",
                platform=p["platform"],
                text=p["text"],
                source_hint=p["source_hint"],
                permalink=p.get("permalink"),
                cluster_id=None,
                state_code=None,
                district_id=None,
                resolution_method=None,
                resolution_confidence=None,
                region_id=None,
            )
        )
    if dropped:
        print(f"[source_posts] dropped {dropped} low-signal post(s) before clustering", flush=True)

    posts = await _filter_by_relevance(posts, state["query"], framings, llm)
    state["posts"] = posts
    state["posts_collected"] = len(posts)

    if not posts and youtube_quota_hit:
        # Distinct from an ordinary "no relevant content found" empty result
        # -- this means sourcing never got a real chance to run at all. Every
        # downstream stage already degrades gracefully on zero posts (this is
        # a StatusEvent, not a StreamErrorEvent, specifically so the run still
        # completes and the answer panel can still show research-grounded
        # content), but a bare "0 posts" ticker at the very end reads as "no
        # relevant content" rather than "the API couldn't even be asked" --
        # say the real reason up front instead of leaving it to be inferred.
        print(
            "[source_posts] YouTube quota exhausted and no other real source configured "
            "(has_reddit=false) -- this run will have zero real posts to cluster.",
            flush=True,
        )
        await emit(
            StatusEvent(
                queryRunId=state["query_run_id"],
                ticker=(
                    "YouTube's daily API quota is exhausted, and no Reddit credentials are "
                    "configured — no real posts could be collected this run. Resolved "
                    "content and the map will be empty; the answer panel may still show "
                    "research-grounded findings. Try again after the quota resets."
                ),
                phase="sourcing",
                counts=counts_from_state(state),
                progress=0.1,
            )
        )
        return state

    await emit(
        StatusEvent(
            queryRunId=state["query_run_id"],
            ticker=(
                f"Collected {len(posts)} posts across {len(target_states)} states · "
                "resolving districts…"
            ),
            phase="sourcing",
            counts=counts_from_state(state),
            progress=0.1,
        )
    )
    return state


def _bind(fn, **extra):
    async def wrapped(state: PipelineState) -> PipelineState:
        return await fn(state, **extra)

    return wrapped


def build_graph(emit: EmitFn, llm: LLMClient, settings: Settings, mode: ResearchMode):
    """Constructs and compiles the pipeline graph for one request. `mode`
    selects the topology (see module docstring) — known before `ainvoke` runs,
    so this is a one-time branch at construction, not a runtime predicate."""
    reddit = get_reddit_connector(settings)
    youtube = get_youtube_connector(settings)
    gazetteer = load_gazetteer()

    graph = StateGraph(PipelineState)
    graph.add_node(
        "source",
        _bind(source_posts, emit=emit, reddit=reddit, youtube=youtube, llm=llm, gazetteer=gazetteer),
    )
    graph.add_node("research", _bind(gather_research, emit=emit, llm=llm, gazetteer=gazetteer))

    if mode == "extrahigh":
        district_centroids = load_district_centroids()
        graph.add_node(
            "geo_resolve",
            _bind(
                resolve_posts_geography,
                emit=emit,
                llm=llm,
                gazetteer=gazetteer,
                subreddit_lookup=lookup_subreddit,
                script_region_detect=detect_script_region,
            ),
        )
        graph.add_node(
            "infer_regions",
            _bind(
                infer_regions,
                emit=emit,
                llm=llm,
                gazetteer=gazetteer,
                district_centroids=district_centroids,
            ),
        )
        graph.add_node("cluster", _bind(cluster_viewpoints_per_region, emit=emit, llm=llm))
        graph.add_node("resolve", _bind(finalize_districts, emit=emit, llm=llm))
        graph.add_node("deflect", _bind(extract_deflections_per_region, emit=emit, llm=llm))
        graph.add_node("deflect_states", _bind(extract_deflections_per_state, emit=emit, llm=llm))
        graph.add_node("synthesize", _bind(synthesize_answer, emit=emit, llm=llm))
        graph.add_node("condition_regions", _bind(condition_regions, emit=emit, llm=llm))
        graph.add_node("condition_states", _bind(condition_states, emit=emit, llm=llm))

        graph.set_entry_point("source")
        graph.add_edge("source", "research")
        graph.add_edge("research", "geo_resolve")
        graph.add_edge("geo_resolve", "infer_regions")
        graph.add_edge("infer_regions", "cluster")
        graph.add_edge("cluster", "resolve")
        graph.add_edge("resolve", "deflect")
        graph.add_edge("deflect", "deflect_states")
        graph.add_edge("deflect_states", "synthesize")
        graph.add_edge("synthesize", "condition_regions")
        graph.add_edge("condition_regions", "condition_states")
        graph.add_edge("condition_states", END)
    else:
        graph.add_node("cluster", _bind(cluster_viewpoints, emit=emit, llm=llm))
        graph.add_node(
            "resolve",
            _bind(
                resolve_districts,
                emit=emit,
                llm=llm,
                gazetteer=gazetteer,
                subreddit_lookup=lookup_subreddit,
                script_region_detect=detect_script_region,
            ),
        )
        graph.add_node("deflect", _bind(extract_deflections, emit=emit, llm=llm))
        graph.add_node("synthesize", _bind(synthesize_answer, emit=emit, llm=llm))

        graph.set_entry_point("source")
        graph.add_edge("source", "research")
        graph.add_edge("research", "cluster")
        graph.add_edge("cluster", "resolve")
        graph.add_edge("resolve", "deflect")
        graph.add_edge("deflect", "synthesize")
        graph.add_edge("synthesize", END)

    return graph.compile()


async def run_pipeline(
    query: str,
    mode: ResearchMode,
    provider: LlmProvider,
    query_run_id: str,
    query_type: str,
    settings: Settings,
    emit: EmitFn,
) -> PipelineState:
    """Runs one full pass. Caller has already emitted `query_started` and will
    emit `done`/`error` based on this function's return/exception."""
    llm = get_llm_client(settings, provider)
    state = new_pipeline_state(query_run_id, query, mode)
    state["query_type"] = query_type
    graph = build_graph(emit, llm, settings, mode)
    return await graph.ainvoke(state)
